// Generated by SandPiper(TM) 1.12-2022/01/27-beta from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For $count.
wire [BITS-1:0] L0_count_a0;
reg  [BITS-1:0] L0_count_a1;

// For $la_write.
wire [31:0] L0_la_write_a0;

// For $rdata.
wire [31:0] L0_rdata_a0;

// For $ready.
wire L0_ready_a0;
reg  L0_ready_a1;

// For $rst.
wire L0_rst_a0;

// For $valid.
wire L0_valid_a0;

// For $wdata.
wire [31:0] L0_wdata_a0;

// For $wstrb.
wire [3:0] L0_wstrb_a0;



generate

   // For $count.
   always @(posedge clk) L0_count_a1[BITS-1:0] <= L0_count_a0[BITS-1:0];

   // For $ready.
   always @(posedge clk) L0_ready_a1 <= L0_ready_a0;



endgenerate




generate   // This is awkward, but we need to go into 'generate' context in the line that `includes the declarations file.
