set ::env(PDK) "gf180mcuD"
set ::env(PDKPATH) "/home/passant/OpenLane/pdks/gf180mcuD"
set ::env(STD_CELL_LIBRARY) "gf180mcu_fd_sc_mcu7t5v0"
set ::env(SCLPATH) "/home/passant/OpenLane/pdks/gf180mcuD/gf180mcu_fd_sc_mcu7t5v0"
set ::env(DESIGN_DIR) "/home/passant/efabless/gf180_upw/openlane/user_proj_example"
set ::env(DESIGN_NAME) "user_proj_example"
set ::env(VERILOG_FILES) "/home/passant/efabless/gf180_upw/openlane/user_proj_example/../../verilog/rtl/defines.v /home/passant/efabless/gf180_upw/openlane/user_proj_example/../../verilog/rtl/user_proj_example.v"
set ::env(DESIGN_IS_CORE) "0"
set ::env(CLOCK_PORT) "wb_clk_i"
set ::env(CLOCK_NET) "counter.clk"
set ::env(CLOCK_PERIOD) "24.0"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 2800 1760"
set ::env(FP_PIN_ORDER_CFG) "/home/passant/efabless/gf180_upw/openlane/user_proj_example/pin_order.cfg"
set ::env(PL_BASIC_PLACEMENT) "0"
set ::env(PL_TARGET_DENSITY) "0.45"
set ::env(FP_CORE_UTIL) "40"
set ::env(MAX_FANOUT_CONSTRAINT) "4"
set ::env(RT_MAX_LAYER) "Metal4"
set ::env(VDD_NETS) "vdd"
set ::env(GND_NETS) "vss"
set ::env(BASE_SDC_FILE) "/home/passant/efabless/gf180_upw/openlane/user_proj_example/base_user_proj_example.sdc"
set ::env(RUN_HEURISTIC_DIODE_INSERTION) "1"
set ::env(RUN_CVC) "1"
set ::env(QUIT_ON_LINTER_ERRORS) "0"
