// Generated by SandPiper(TM) 1.12-2022/01/27-beta from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For $count.
logic [BITS-1:0] L0_count_a0,
                 L0_count_a1;

// For $la_write.
logic [31:0] L0_la_write_a0;

// For $rdata.
logic [31:0] L0_rdata_a0;

// For $ready.
logic L0_ready_a0,
      L0_ready_a1;

// For $rst.
logic L0_rst_a0;

// For $valid.
logic L0_valid_a0;

// For $wdata.
logic [31:0] L0_wdata_a0;

// For $wstrb.
logic [3:0] L0_wstrb_a0;



generate

   // For $count.
   always_ff @(posedge clk) L0_count_a1[BITS-1:0] <= L0_count_a0[BITS-1:0];

   // For $ready.
   always_ff @(posedge clk) L0_ready_a1 <= L0_ready_a0;



endgenerate




generate   // This is awkward, but we need to go into 'generate' context in the line that `includes the declarations file.
