`define WMASK_SIZE 4
`define ADDR_SIZE 16
`define DATA_SIZE 32
`define SELECT_SIZE 4
`define MAX_CHIPS 16
`define PORT_SIZE `DATA_SIZE+`DATA_SIZE+`WMASK_SIZE+2
`define TOTAL_SIZE 2*`PORT_SIZE + `SELECT_SIZE
